name: Create Release

on:
  workflow_dispatch:
    inputs:
      binary_name:
        description: 'dnshammer'
        required: true
        default: 'dnshammer'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Build binary
        run: v -prod -o ${{ github.event.inputs.binary_name }} ./dnsh.v

      - name: Create Release + Upload Binary
        uses: ncipollo/release-action@v1
        with:
          tag: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          artifacts: ${{ github.event.inputs.binary_name }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
